embeddings {
  tensor_name: "embedding:0"
  metadata_path: "/Users/zoe/Documents/GitHub/July-NLP/TF/DATAGURU/Lec 05/projector/projector/metadata.tsv"
  sprite {
    image_path: "/Users/zoe/Documents/GitHub/July-NLP/TF/DATAGURU/Lec 05/projector/data/mnist_10k_sprite.png"
    single_image_dim: 28
    single_image_dim: 28
  }
}
